# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_player_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seed', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
