# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0003_auto_20160412_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='picks.Region'),
            preserve_default=False,
        ),
    ]
