# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0004_auto_20160412_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
